# Generated by Django 4.2.20 on 2025-05-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guia',
            name='telefono',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pilotocliente',
            name='telefono',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='viaje',
            name='pilotos',
            field=models.ManyToManyField(blank=True, related_name='viajes', to='viajes.pilotocliente'),
        ),
    ]
